algoritmo "covid"

var
p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15 : caracter
C1, C2, C3 , C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, C15 : inteiro
M1,M2, M3, M4, M5, M6, M7, M8, M9, M10, M11, M12, M13, M14, M15 : inteiro
   mediana, media : real
inicio

escreva("Digite o nome do País: ")
leia(p1)
escreva("Digite o numero de casos: ")
leia(C1)
escreva("Digite o numero de mortes: ")
leia(M1)


escreva("Digite o nome do País: ")
leia(p2)
escreva("Digite o numero de casos: ")
leia(C2)
escreva("Digite o numero de mortes: ")
leia(M2)


escreva("Digite o nome do País: ")
leia(p3)
escreva("Digite o numero de casos: ")
leia(C3)
escreva("Digite o numero de mortes: ")
leia(M3)


escreva("Digite o nome do País: ")
leia(p4)
escreva("Digite o numero de casos: ")
leia(C4)
escreva("Digite o numero de mortes: ")
leia(M4)


escreva("Digite o nome do País: ")
leia(p5)
escreva("Digite o numero de casos: ")
leia(C5)
escreva("Digite o numero de mortes: ")
leia(M5)


escreva("Digite o nome do País: ")
leia(p6)
escreva("Digite o numero de casos: ")
leia(C6)
escreva("Digite o numero de mortes: ")
leia(M6)


escreva("Digite o nome do País: ")
leia(p7)
escreva("Digite o numero de casos: ")
leia(C7)
escreva("Digite o numero de mortes: ")
leia(M7)


escreva("Digite o nome do País: ")
leia(p8)
escreva("Digite o numero de casos: ")
leia(C8)
escreva("Digite o numero de mortes: ")
leia(M8)


escreva("Digite o nome do País: ")
leia(p9)
escreva("Digite o numero de casos: ")
leia(C9)
escreva("Digite o numero de mortes: ")
leia(M9)


escreva("Digite o nome do País: ")
leia(p10)
escreva("Digite o numero de casos: ")
leia(C10)
escreva("Digite o numero de mortes: ")
leia(M10)


escreva("Digite o nome do País: ")
leia(p11)
escreva("Digite o numero de casos: ")
leia(C11)
escreva("Digite o numero de mortes: ")
leia(M11)


escreva("Digite o nome do País: ")
leia(p12)
escreva("Digite o numero de casos: ")
leia(C12)
escreva("Digite o numero de mortes: ")
leia(M12)


escreva("Digite o nome do País: ")
leia(p13)
escreva("Digite o numero de casos: ")
leia(C13)
escreva("Digite o numero de mortes: ")
leia(M13)


escreva("Digite o nome do País: ")
leia(p14)
escreva("Digite o numero de casos: ")
leia(C14)
escreva("Digite o numero de mortes: ")
leia(M14)

escreva("Digite o nome do País: ")
leia(p15)
escreva("Digite o numero de casos: ")
leia(C15)
escreva("Digite o numero de mortes: ")
leia(M15)


 escreval(p1," casos ", C1," mortes  " ,M1)
  escreval (p2," casos ", C2," mortes  " ,M2)
   escreval








   escreval (p3," casos ", C3," mortes  " ,M3)
    escreval (p4," casos ", C4," mortes  " ,M4)
     escreval (p5," casos ", C5," mortes  " ,M5)
      escreval(p6," casos ", C6," mortes  " ,M6)
       escreval(p7," casos ", C7," mortes  " ,M7)
        escreval(p8," casos ", C8," mortes  " ,M8)
         escreval(p9," casos ", C9," mortes  " ,M9)
          escreval(p10," casos ", C10," mortes  " ,M10)
           escreval(p11," casos ", C11," mortes  " ,M11)
            escreval(p12," casos ", C12," mortes  " ,M12)
             escreval(p13," casos ", C13," mortes  " ,M13)
              escreval(p14," casos ", C14," mortes  " ,M14)
               escreval(p15," casos ", C15," mortes  " ,M15)




media <- ( (C1+C2+C3+C4+C5+C6+C7+C8+C9+C10+C11+C12+C13+C14+C15) /15)
mediana <- (C7+C8) / 2

escreval("a media de casos ",media)
escreval("mediana ",mediana)





fimalgoritmo